version: "3.8"

services:
  frontend:
    container_name: frontend-react
    image: frontend-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
  storybook:
    container_name: frontend-storybook
    image: frontend-storybook
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run storybook
    ports:
      - 6006:6006
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - frontend
