version: '3.8'
services:
  frontend-react:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${VITE_APP_PORT}:${VITE_APP_PORT}"
    volumes:
      - ./dist:/app/
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend-react
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
